import React from 'react';
import { LayoutDashboard, Users, GraduationCap, ClipboardCheck, BookOpen, CalendarDays, FileText, BarChart3, LogOut } from 'lucide-react';

export const NAV={admin:[['dashboard','Dashboard',LayoutDashboard],['students','Students',Users],['faculty','Faculty',GraduationCap],['academics','Academic Setup',BookOpen],['attendance','Attendance',ClipboardCheck],['exams','Examinations',FileText],['assignments','Assignments',FileText],['timetable','Timetable',CalendarDays],['leave','Leave Approvals',FileText],['notices','Notices',FileText],['reports','Reports',BarChart3]],faculty:[['dashboard','My Dashboard',LayoutDashboard],['students','My Students',Users],['attendance','Attendance',ClipboardCheck],['assignments','Assignments',FileText],['results','Marks & Results',FileText],['timetable','My Timetable',CalendarDays],['leave','My Leave',FileText],['notices','Notices',FileText],['performance','Performance',BarChart3]],student:[['dashboard','My Dashboard',LayoutDashboard],['profile','My Profile',Users],['courses','Course Registration',BookOpen],['attendance','My Attendance',ClipboardCheck],['assignments','Assignments',FileText],['exams','Exams & Results',FileText],['timetable','My Timetable',CalendarDays],['leave','Leave Application',FileText],['documents','Documents & ID',FileText],['notices','Notices',FileText]]};

export default function Shell({user,page,onNavigate,onLogout,children}){
 const nav=NAV[user.role]||[];
 const logout=()=>{if(onLogout)onLogout();else{localStorage.removeItem('ocms_user');location.reload()}};
 return <div className="app-shell"><aside className="sidebar"><div className="logo"><span>O</span>CMS</div><div className="profile"><b>{user.name}</b><small>{user.email}</small></div><div className="workspace">{user.role.toUpperCase()} / WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>onNavigate(key)}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-bottom"><button onClick={logout}><LogOut size={17}/>Sign out</button></div></aside><main className="main"><header><div><small>OCMS / {user.role.toUpperCase()}</small><h1>{nav.find(x=>x[0]===page)?.[1]||'Dashboard'}</h1></div><div className="user-pill">{user.name}</div></header><section className="content">{children}</section></main></div>;
}
